name: test build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - run: ./gradlew build --stacktrace
